export const codeByLang = {    
    "two-sum-brute": {
        javascript:["function twoSum(nums, target) {","  for (let i = 0; i < nums.length; i++) {","    for (let j = i+1; j < nums.length; j++) {","      if (nums[i] + nums[j] === target)","        return [i, j];","    }","  }","  return [];","}"],
        python:["def two_sum(nums, target):","    for i in range(len(nums)):","        for j in range(i+1, len(nums)):","            if nums[i] + nums[j] == target:","                return [i, j]","    return []"],
        java:["public int[] twoSum(int[] nums, int target) {","    for (int i=0; i<nums.length; i++)","        for (int j=i+1; j<nums.length; j++)","            if (nums[i]+nums[j]==target)","                return new int[]{i,j};","    return new int[]{};","}"],
    },
    "two-sum-hash": {
        javascript:["function twoSum(nums, target) {","  const map = new Map();","  for (let i = 0; i < nums.length; i++) {","    const comp = target - nums[i];","    if (map.has(comp)) return [map.get(comp), i];","    map.set(nums[i], i);","  }","  return [];","}"],
        python:["def two_sum(nums, target):","    seen = {}","    for i, num in enumerate(nums):","        comp = target - num","        if comp in seen: return [seen[comp], i]","        seen[num] = i","    return []"],
        java:["public int[] twoSum(int[] nums, int target) {","    Map<Integer,Integer> map = new HashMap<>();","    for (int i=0; i<nums.length; i++) {","        int comp = target - nums[i];","        if (map.containsKey(comp))","            return new int[]{map.get(comp), i};","        map.put(nums[i], i);","    }","    return new int[]{};","}"],
    },
    "sliding-window": {
        javascript:["function lengthOfLongestSubstring(s) {","  let left=0, maxLen=0;","  const seen = new Set();","  for (let right=0; right<s.length; right++) {","    while (seen.has(s[right])) {","      seen.delete(s[left++]);","    }","    seen.add(s[right]);","    maxLen = Math.max(maxLen, right-left+1);","  }","  return maxLen;","}"],
        python:["def length_of_longest_substring(s):","    left=0; max_len=0; seen=set()","    for right in range(len(s)):","        while s[right] in seen:","            seen.remove(s[left]); left+=1","        seen.add(s[right])","        max_len = max(max_len, right-left+1)","    return max_len"],
        java:["public int lengthOfLongestSubstring(String s) {","    int left=0, maxLen=0;","    Set<Character> seen = new HashSet<>();","    for (int right=0; right<s.length(); right++) {","        while (seen.contains(s.charAt(right)))","            seen.remove(s.charAt(left++));","        seen.add(s.charAt(right));","        maxLen = Math.max(maxLen, right-left+1);","    }","    return maxLen;","}"],
    },
    "kadane": {
        javascript:["function maxSubArray(nums) {","  let maxSum = nums[0];","  let currSum = nums[0];","  for (let i = 1; i < nums.length; i++) {","    currSum = Math.max(nums[i], currSum + nums[i]);","    maxSum  = Math.max(maxSum, currSum);","  }","  return maxSum;","}"],
        python:["def max_sub_array(nums):","    max_sum = curr_sum = nums[0]","    for num in nums[1:]:","        curr_sum = max(num, curr_sum + num)","        max_sum  = max(max_sum, curr_sum)","    return max_sum"],
        java:["public int maxSubArray(int[] nums) {","    int maxSum=nums[0], currSum=nums[0];","    for (int i=1; i<nums.length; i++) {","        currSum = Math.max(nums[i], currSum+nums[i]);","        maxSum  = Math.max(maxSum, currSum);","    }","    return maxSum;","}"],
    },
    "trapping-rain": {
        javascript:["function trap(height) {","  let left=0, right=height.length-1;","  let leftMax=0, rightMax=0, water=0;","  while (left < right) {","    if (height[left] < height[right]) {","      if (height[left] >= leftMax) leftMax = height[left];","      else water += leftMax - height[left];","      left++;","    } else {","      if (height[right] >= rightMax) rightMax = height[right];","      else water += rightMax - height[right];","      right--;","    }","  }","  return water;","}"],
        python:["def trap(height):","    left,right=0,len(height)-1","    left_max=right_max=water=0","    while left < right:","        if height[left] < height[right]:","            if height[left]>=left_max: left_max=height[left]","            else: water+=left_max-height[left]","            left+=1","        else:","            if height[right]>=right_max: right_max=height[right]","            else: water+=right_max-height[right]","            right-=1","    return water"],
        java:["public int trap(int[] h) {","    int l=0,r=h.length-1,lm=0,rm=0,w=0;","    while (l<r) {","        if (h[l]<h[r]) {","            if (h[l]>=lm) lm=h[l]; else w+=lm-h[l];","            l++;","        } else {","            if (h[r]>=rm) rm=h[r]; else w+=rm-h[r];","            r--;","        }","    }","    return w;","}"],
    },
    "next-greater": {
        javascript:["function nextGreaterElement(nums) {","  const result = new Array(nums.length).fill(-1);","  const stack = [];","  for (let i = 0; i < nums.length; i++) {","    while (stack.length && nums[stack[stack.length-1]] < nums[i]) {","      const idx = stack.pop();","      result[idx] = nums[i];","    }","    stack.push(i);","  }","  return result;","}"],
        python:["def next_greater(nums):","    result = [-1]*len(nums)","    stack = []","    for i,num in enumerate(nums):","        while stack and nums[stack[-1]] < num:","            idx = stack.pop()","            result[idx] = num","        stack.append(i)","    return result"],
        java:["public int[] nextGreaterElement(int[] nums) {","    int[] res = new int[nums.length];","    Arrays.fill(res, -1);","    Deque<Integer> stack = new ArrayDeque<>();","    for (int i=0; i<nums.length; i++) {","        while (!stack.isEmpty() && nums[stack.peek()]<nums[i])","            res[stack.pop()] = nums[i];","        stack.push(i);","    }","    return res;","}"],
    },
    "binary-search-rotated": {
        javascript:["function search(nums, target) {","  let lo=0, hi=nums.length-1;","  while (lo <= hi) {","    const mid = Math.floor((lo+hi)/2);","    if (nums[mid] === target) return mid;","    if (nums[lo] <= nums[mid]) {","      if (nums[lo]<=target && target<nums[mid]) hi=mid-1;","      else lo=mid+1;","    } else {","      if (nums[mid]<target && target<=nums[hi]) lo=mid+1;","      else hi=mid-1;","    }","  }","  return -1;","}"],
        python:["def search(nums, target):","    lo, hi = 0, len(nums)-1","    while lo <= hi:","        mid = (lo+hi)//2","        if nums[mid]==target: return mid","        if nums[lo] <= nums[mid]:","            if nums[lo]<=target<nums[mid]: hi=mid-1","            else: lo=mid+1","        else:","            if nums[mid]<target<=nums[hi]: lo=mid+1","            else: hi=mid-1","    return -1"],
        java:["public int search(int[] nums, int target) {","    int lo=0, hi=nums.length-1;","    while (lo<=hi) {","        int mid=(lo+hi)/2;","        if (nums[mid]==target) return mid;","        if (nums[lo]<=nums[mid]) {","            if (nums[lo]<=target && target<nums[mid]) hi=mid-1;","            else lo=mid+1;","        } else {","            if (nums[mid]<target && target<=nums[hi]) lo=mid+1;","            else hi=mid-1;","        }","    }","    return -1;","}"],
    },
    "merge-sort": {
        javascript:["function mergeSort(arr, l, r) {","  if (l >= r) return;","  const mid = Math.floor((l+r)/2);","  mergeSort(arr, l, mid);","  mergeSort(arr, mid+1, r);","  merge(arr, l, mid, r);","}","function merge(arr, l, mid, r) {","  const L=arr.slice(l,mid+1), R=arr.slice(mid+1,r+1);","  let i=0,j=0,k=l;","  while (i<L.length && j<R.length)","    arr[k++]=L[i]<=R[j]?L[i++]:R[j++];","  while (i<L.length) arr[k++]=L[i++];","  while (j<R.length) arr[k++]=R[j++];","}"],
        python:["def merge_sort(arr):","    if len(arr)<=1: return arr","    mid=len(arr)//2","    L=merge_sort(arr[:mid])","    R=merge_sort(arr[mid:])","    return merge(L,R)","def merge(L,R):","    res,i,j=[],0,0","    while i<len(L) and j<len(R):","        if L[i]<=R[j]: res.append(L[i]); i+=1","        else: res.append(R[j]); j+=1","    return res+L[i:]+R[j:]"],
        java:["void mergeSort(int[] a, int l, int r) {","    if (l>=r) return;","    int mid=(l+r)/2;","    mergeSort(a,l,mid); mergeSort(a,mid+1,r);","    merge(a,l,mid,r);","}","void merge(int[] a,int l,int mid,int r) {","    int[] L=Arrays.copyOfRange(a,l,mid+1);","    int[] R=Arrays.copyOfRange(a,mid+1,r+1);","    int i=0,j=0,k=l;","    while(i<L.length&&j<R.length)","        a[k++]=L[i]<=R[j]?L[i++]:R[j++];","}"],
    },
    "quick-sort": {
        javascript:["function quickSort(arr, lo, hi) {","  if (lo<hi) {","    const pi=partition(arr,lo,hi);","    quickSort(arr,lo,pi-1);","    quickSort(arr,pi+1,hi);","  }","}","function partition(arr, lo, hi) {","  const pivot=arr[hi]; let i=lo-1;","  for (let j=lo; j<hi; j++)","    if (arr[j]<=pivot) { i++; [arr[i],arr[j]]=[arr[j],arr[i]]; }","  [arr[i+1],arr[hi]]=[arr[hi],arr[i+1]];","  return i+1;","}"],
        python:["def quick_sort(arr, lo, hi):","    if lo<hi:","        pi=partition(arr,lo,hi)","        quick_sort(arr,lo,pi-1)","        quick_sort(arr,pi+1,hi)","def partition(arr, lo, hi):","    pivot=arr[hi]; i=lo-1","    for j in range(lo,hi):","        if arr[j]<=pivot:","            i+=1; arr[i],arr[j]=arr[j],arr[i]","    arr[i+1],arr[hi]=arr[hi],arr[i+1]","    return i+1"],
        java:["void quickSort(int[] a, int lo, int hi) {","    if (lo<hi) {","        int pi=partition(a,lo,hi);","        quickSort(a,lo,pi-1); quickSort(a,pi+1,hi);","    }","}","int partition(int[] a,int lo,int hi) {","    int pivot=a[hi],i=lo-1;","    for(int j=lo;j<hi;j++)","        if(a[j]<=pivot){int t=a[++i];a[i]=a[j];a[j]=t;}","    int t=a[i+1];a[i+1]=a[hi];a[hi]=t;","    return i+1;","}"],
    },
    "bfs": {
        javascript:["function bfs(graph, start) {","  const visited=new Set([start]), queue=[start], order=[];","  while (queue.length) {","    const node=queue.shift(); order.push(node);","    for (const nb of graph[node])","      if (!visited.has(nb)) { visited.add(nb); queue.push(nb); }","  }","  return order;","}"],
        python:["from collections import deque","def bfs(graph, start):","    visited={start}; queue=deque([start]); order=[]","    while queue:","        node=queue.popleft(); order.append(node)","        for nb in graph[node]:","            if nb not in visited:","                visited.add(nb); queue.append(nb)","    return order"],
        java:["List<Integer> bfs(Map<Integer,List<Integer>> g, int s) {","    Set<Integer> vis=new HashSet<>();","    Queue<Integer> q=new LinkedList<>();","    List<Integer> order=new ArrayList<>();","    vis.add(s); q.add(s);","    while (!q.isEmpty()) {","        int node=q.poll(); order.add(node);","        for(int nb:g.get(node))","            if(!vis.contains(nb)){vis.add(nb);q.add(nb);}","    }","    return order;","}"],
    },
    "dfs": {
        javascript:["function dfs(graph, node, visited=new Set()) {","  if (visited.has(node)) return;","  visited.add(node); console.log(node);","  for (const nb of graph[node])","    dfs(graph, nb, visited);","}"],
        python:["def dfs(graph, node, visited=None):","    if visited is None: visited=set()","    if node in visited: return","    visited.add(node); print(node)","    for nb in graph[node]:","        dfs(graph, nb, visited)"],
        java:["void dfs(Map<Integer,List<Integer>> g, int node, Set<Integer> vis) {","    if (vis.contains(node)) return;","    vis.add(node); System.out.println(node);","    for(int nb:g.get(node)) dfs(g,nb,vis);","}"],
    },
    "bfs-shortest": {
        javascript:["function shortestPath(graph, src, dst) {","  const queue=[[src,[src]]], visited=new Set([src]);","  while (queue.length) {","    const [node, path]=queue.shift();","    if (node===dst) return path;","    for (const nb of graph[node]) {","      if (!visited.has(nb)) {","        visited.add(nb);","        queue.push([nb, [...path, nb]]);","      }","    }","  }","  return null;","}"],
        python:["from collections import deque","def shortest_path(graph, src, dst):","    queue=deque([(src,[src])])","    visited={src}","    while queue:","        node,path=queue.popleft()","        if node==dst: return path","        for nb in graph[node]:","            if nb not in visited:","                visited.add(nb)","                queue.append((nb,path+[nb]))","    return None"],
        java:["List<Integer> shortestPath(Map<Integer,List<Integer>> g,int src,int dst){","    Queue<List<Integer>> q=new LinkedList<>();","    Set<Integer> vis=new HashSet<>();","    q.add(Arrays.asList(src)); vis.add(src);","    while(!q.isEmpty()){","        List<Integer> path=q.poll();","        int node=path.get(path.size()-1);","        if(node==dst) return path;","        for(int nb:g.get(node)) if(!vis.contains(nb)){","            vis.add(nb);","            List<Integer> np=new ArrayList<>(path); np.add(nb);","            q.add(np);}","    } return null;","}"],
    },
    "number-of-islands": {
        javascript:["function numIslands(grid) {","  let count = 0;","  for (let r=0; r<grid.length; r++)","    for (let c=0; c<grid[0].length; c++)","      if (grid[r][c]==='1') { dfs(grid,r,c); count++; }","  return count;","}","function dfs(grid, r, c) {","  if (r<0||r>=grid.length||c<0||c>=grid[0].length||grid[r][c]!=='1') return;","  grid[r][c]='0';","  dfs(grid,r+1,c); dfs(grid,r-1,c);","  dfs(grid,r,c+1); dfs(grid,r,c-1);","}"],
        python:["def num_islands(grid):","    count=0","    for r in range(len(grid)):","        for c in range(len(grid[0])):","            if grid[r][c]=='1':","                dfs(grid,r,c); count+=1","    return count","def dfs(grid,r,c):","    if r<0 or r>=len(grid) or c<0 or c>=len(grid[0]) or grid[r][c]!='1': return","    grid[r][c]='0'","    for dr,dc in [(1,0),(-1,0),(0,1),(0,-1)]:","        dfs(grid,r+dr,c+dc)"],
        java:["public int numIslands(char[][] grid) {","    int count=0;","    for(int r=0;r<grid.length;r++)","        for(int c=0;c<grid[0].length;c++)","            if(grid[r][c]=='1'){dfs(grid,r,c);count++;}","    return count;","}","void dfs(char[][] g,int r,int c){","    if(r<0||r>=g.length||c<0||c>=g[0].length||g[r][c]!='1') return;","    g[r][c]='0';","    dfs(g,r+1,c);dfs(g,r-1,c);dfs(g,r,c+1);dfs(g,r,c-1);","}"],
    },
    "n-queens": {
        javascript:["function solveNQueens(n) {","  const board=Array.from({length:n},()=>Array(n).fill('.'));","  const solutions=[];","  function backtrack(row) {","    if (row===n) { solutions.push(board.map(r=>r.join(''))); return; }","    for (let col=0; col<n; col++) {","      if (isValid(board,row,col,n)) {","        board[row][col]='Q';","        backtrack(row+1);","        board[row][col]='.';","      }","    }","  }","  backtrack(0); return solutions;","}"],
        python:["def solve_n_queens(n):","    board=[['.']*n for _ in range(n)]","    solutions=[]","    def backtrack(row):","        if row==n: solutions.append([''.join(r) for r in board]); return","        for col in range(n):","            if is_valid(board,row,col,n):","                board[row][col]='Q'","                backtrack(row+1)","                board[row][col]='.'","    backtrack(0); return solutions"],
        java:["List<List<String>> solveNQueens(int n) {","    char[][] board=new char[n][n];","    for(char[] r:board) Arrays.fill(r,'.');","    List<List<String>> res=new ArrayList<>();","    backtrack(board,0,n,res);","    return res;","}","void backtrack(char[][] b,int row,int n,List<List<String>> res){","    if(row==n){List<String> s=new ArrayList<>();","        for(char[] r:b) s.add(new String(r)); res.add(s); return;}","    for(int col=0;col<n;col++)","        if(isValid(b,row,col,n)){b[row][col]='Q';","            backtrack(b,row+1,n,res); b[row][col]='.';}}"],
    },
    "coin-change": {
        javascript:["function coinChange(coins, amount) {","  const dp = Array(amount+1).fill(Infinity);","  dp[0] = 0;","  for (let i=1; i<=amount; i++) {","    for (const coin of coins) {","      if (coin <= i && dp[i-coin]+1 < dp[i])","        dp[i] = dp[i-coin]+1;","    }","  }","  return dp[amount]===Infinity ? -1 : dp[amount];","}"],
        python:["def coin_change(coins, amount):","    dp=[float('inf')]*(amount+1)","    dp[0]=0","    for i in range(1,amount+1):","        for coin in coins:","            if coin<=i and dp[i-coin]+1<dp[i]:","                dp[i]=dp[i-coin]+1","    return -1 if dp[amount]==float('inf') else dp[amount]"],
        java:["public int coinChange(int[] coins, int amount) {","    int[] dp=new int[amount+1];","    Arrays.fill(dp, Integer.MAX_VALUE);","    dp[0]=0;","    for(int i=1;i<=amount;i++)","        for(int coin:coins)","            if(coin<=i && dp[i-coin]!=Integer.MAX_VALUE)","                dp[i]=Math.min(dp[i],dp[i-coin]+1);","    return dp[amount]==Integer.MAX_VALUE?-1:dp[amount];","}"],
    },
};