export const problemStatements = {
  "two-sum-brute": { title:"Two Sum", difficulty:"Easy", diffColor:"text-emerald-400", platform:"LeetCode #1",
    description:"Given an array of integers and a target, return indices of two numbers that add up to target. Brute force checks every pair.",
    constraints:["2 ≤ nums.length ≤ 10⁴","Only one valid answer"],
    examples:[{input:"nums=[2,7,11,15], target=9",output:"[0,1]",reason:"2+7=9"}]},
  "two-sum-hash": { title:"Two Sum", difficulty:"Easy", diffColor:"text-emerald-400", platform:"LeetCode #1",
    description:"Optimal O(n) solution using a hash map. For each element, check if its complement (target - num) already exists in the map.",
    constraints:["2 ≤ nums.length ≤ 10⁴","Only one valid answer"],
    examples:[{input:"nums=[2,7,11,15], target=9",output:"[0,1]",reason:"complement(2)=7 found at index 1"}]},
  "sliding-window": { title:"Longest Substring Without Repeating Characters", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #3",
    description:"Find the length of the longest substring without repeating characters. Use a sliding window — expand right, shrink left on duplicates.",
    constraints:["0 ≤ s.length ≤ 5×10⁴"],
    examples:[{input:'s="abcabcbb"',output:"3",reason:'"abc" is longest unique window'}]},
  "kadane": { title:"Maximum Subarray (Kadane's Algorithm)", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #53",
    description:"Find the contiguous subarray with the largest sum. Kadane's algorithm tracks currentSum and maxSum in a single pass — if currentSum goes negative, reset it.",
    constraints:["1 ≤ nums.length ≤ 10⁵","-10⁴ ≤ nums[i] ≤ 10⁴"],
    examples:[{input:"nums=[-2,1,-3,4,-1,2,1,-5,4]",output:"6",reason:"Subarray [4,-1,2,1] has sum 6"}]},
  "trapping-rain": { title:"Trapping Rain Water", difficulty:"Hard", diffColor:"text-red-400", platform:"LeetCode #42",
    description:"Given elevation heights, compute how much rain water can be trapped. Two-pointer approach: track leftMax and rightMax, water at each bar = min(leftMax, rightMax) - height[i].",
    constraints:["1 ≤ n ≤ 2×10⁴","0 ≤ height[i] ≤ 10⁵"],
    examples:[{input:"height=[0,1,0,2,1,0,1,3,2,1,2,1]",output:"6",reason:"Water trapped between elevations = 6 units"}]},
  "next-greater": { title:"Next Greater Element I", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #496",
    description:"For each element, find the next greater element to its right. Use a monotonic decreasing stack — pop elements smaller than current, they've found their next greater.",
    constraints:["1 ≤ nums.length ≤ 10⁴","All elements distinct"],
    examples:[{input:"nums=[2,1,5,3,4]",output:"[5,5,-1,4,-1]",reason:"Next greater of 2 is 5, of 1 is 5, of 5 is -1..."}]},
  "binary-search-rotated": { title:"Search in Rotated Sorted Array", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #33",
    description:"Search a target in a sorted array that has been rotated at some pivot. At each step, determine which half is sorted, then check if target lies in that half.",
    constraints:["1 ≤ nums.length ≤ 5000","All values unique"],
    examples:[{input:"nums=[4,5,6,7,0,1,2], target=0",output:"4",reason:"Target 0 is at index 4"}]},
  "merge-sort": { title:"Sort an Array — Merge Sort", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #912",
    description:"Divide-and-conquer: recursively split array in half, sort each half, merge sorted halves. The recursion tree shows call depth and merge order.",
    constraints:["1 ≤ nums.length ≤ 5×10⁴"],
    examples:[{input:"nums=[5,2,3,1]",output:"[1,2,3,5]",reason:"Split → sort halves → merge"}]},
  "quick-sort": { title:"Sort an Array — Quick Sort", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #912",
    description:"Pick pivot (last element), partition array around it, recursively sort each partition. In-place and cache-friendly but O(n²) worst case.",
    constraints:["1 ≤ nums.length ≤ 5×10⁴"],
    examples:[{input:"nums=[3,2,1,5,6,4]",output:"[1,2,3,4,5,6]",reason:"Pivot partitioning places each element correctly"}]},
  "bfs": { title:"Breadth-First Search", difficulty:"Medium", diffColor:"text-amber-400", platform:"Graph Traversal",
    description:"Visit all nodes level by level using a queue. BFS explores all neighbors before going deeper — guarantees shortest path in unweighted graphs.",
    constraints:["1 ≤ V ≤ 100","Graph may be disconnected"],
    examples:[{input:"graph={0:[1,2],1:[3,4],2:[5]}, start=0",output:"[0,1,2,3,4,5]",reason:"Level 0:[0], Level 1:[1,2], Level 2:[3,4,5]"}]},
  "dfs": { title:"Depth-First Search", difficulty:"Medium", diffColor:"text-amber-400", platform:"Graph Traversal",
    description:"Explore as deep as possible before backtracking. Uses the call stack recursively. Foundation for cycle detection, topological sort, and connected components.",
    constraints:["1 ≤ V ≤ 100","Graph may be disconnected"],
    examples:[{input:"graph={0:[1,2],1:[3,4],2:[5]}, start=0",output:"[0,1,3,4,2,5]",reason:"Go deep on branch 1 first, then backtrack to 2"}]},
  "bfs-shortest": { title:"BFS Shortest Path", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #1091",
    description:"Find shortest path between two nodes in an unweighted graph using BFS. Track parent pointers to reconstruct the path. Distance = number of edges traversed.",
    constraints:["1 ≤ V ≤ 100","Graph is connected"],
    examples:[{input:"graph={0:[1,2],1:[3],2:[3]}, src=0, dst=3",output:"Path: 0→2→3 (len=2)",reason:"BFS finds shortest — both paths exist but 0→2→3 ties with 0→1→3"}]},
  "number-of-islands": { title:"Number of Islands", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #200",
    description:"Given a 2D grid of '1' (land) and '0' (water), count the number of islands. Use DFS to flood-fill each island — mark visited land to avoid recounting.",
    constraints:["1 ≤ rows, cols ≤ 300","grid[i][j] is '0' or '1'"],
    examples:[{input:'grid=[["1","1","0"],["1","0","0"],["0","0","1"]]',output:"2",reason:"Two separate land masses"}]},
  "n-queens": { title:"N-Queens", difficulty:"Hard", diffColor:"text-red-400", platform:"LeetCode #51",
    description:"Place N queens on an N×N chessboard so no two queens attack each other. Use backtracking — place queen in each row, recurse, backtrack if conflict. Visualize the board state at each step.",
    constraints:["1 ≤ n ≤ 9"],
    examples:[{input:"n=4",output:'[[".Q..","...Q","Q...","..Q."],["..Q.","Q...","...Q",".Q.."]]',reason:"2 solutions for 4-queens"}]},
  "coin-change": { title:"Coin Change", difficulty:"Medium", diffColor:"text-amber-400", platform:"LeetCode #322",
    description:"Given coin denominations and an amount, find the minimum number of coins to make up that amount. Bottom-up DP: dp[i] = min coins needed for amount i. Build up from dp[0]=0.",
    constraints:["1 ≤ coins.length ≤ 12","0 ≤ amount ≤ 10⁴"],
    examples:[{input:"coins=[1,5,11], amount=15",output:"3",reason:"11+1+1+1+1 = 4 coins but 5+5+5=3 coins (optimal)"}]},
};